# <font color=green|black>Semana 06 – Início Análise de Dados - Biblioteca Numpy | 21/10/22 </font> 

- #### Parte I – Introdução à análise de dados;
- #### Parte II – Por que Numpy? 
- #### Parte III – Aplicações. 

**Aula:** https://www.youtube.com/watch?v=s76nawflNbk

**Documentação do Numpy:** https://numpy.org/doc/stable/user/absolute_beginners.html

### <font color=green|black>Professores</font>

-  #### Kevyn A. Marcelino
-  #### Ana C. Santos
   
# -------------------------------------------------------------------------

# <font color=green|black> Parte I – Introdução à análise de dados </font> 

- ### 1.1 Introdução a análise e ciência de dados 

![data_analysis.jpg](attachment:data_analysis.jpg)

        1.1.1 O que é
        1.1.2 Passos iniciais de uma análise
            - ETL - Extract, Transform and Load..
        1.1.2 Diferença de Análise e Ciência de Dados
        


- ### 1.2 Bibliotecas

        1.2.1 O que são
        1.2.2 Importância
        1.2.3 Como instalar e importar - Exemplos
            - pip install
            - O que é o PIP?
            - https://pypi.org/
        1.2.4 Criação da primeira biblioteca

#### Instalando

In [ ]:
# Instalando
#pip install numpy
!pip install numpy

#### Convenções na hora de importar

In [ ]:
# Convenções na hora de importar
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### Exemplos de Bibliotecas

- Help
- Shift + Tab


In [ ]:
import this


The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


#### Onde ficam instaladas?

- pip freeze
- C:\Users\"SeuUsuário"\AppData\Local\Programs\Python\Python310\Lib
    - Pode variar um pouco

In [ ]:
pip freeze

aiohttp @ file:///C:/ci/aiohttp_1646806572557/work
aiosignal @ file:///tmp/build/80754af9/aiosignal_1637843061372/work
alabaster @ file:///home/ktietz/src/ci/alabaster_1611921544520/work
anaconda-client @ file:///C:/ci/anaconda-client_1635342725944/work
anaconda-navigator==2.3.0
anaconda-project @ file:///tmp/build/80754af9/anaconda-project_1637161053845/work
anyio @ file:///C:/ci/anyio_1644481921011/work/dist
appdirs==1.4.4
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///C:/ci/argon2-cffi-bindings_1644551690056/work
arrow @ file:///opt/conda/conda-bld/arrow_1649166651673/work
astroid @ file:///C:/ci/astroid_1628063282661/work
astropy @ file:///C:/ci/astropy_1650634291321/work
asttokens @ file:///opt/conda/conda-bld/asttokens_1646925590279/work
async-timeout @ file:///tmp/build/80754af9/async-timeout_1637851218186/work
atomicwrites==1.4.0
attrs @ file:///opt/conda/conda-bld/attrs_1642510447205/work
Automat @ file:///tmp/build/8075

#### Outros Exemplos

In [ ]:
# Exercício conversor de moedas primeira lista:
#!pip install CurrencyConverter
# documentação: https://pypi.org/project/CurrencyConverter/ ou procurar no pypi

from currency_converter import CurrencyConverter

c = CurrencyConverter()
c.convert(100, 'EUR', 'BRL') #BRL

513.7800000000001

In [ ]:
# A lib conversora tem delay de quase uma semana
from datetime import date
c.convert(100, 'EUR', 'BRL', date=date(2021, 10, 21))


658.92

In [ ]:
# Exercicio estatística descritiva lista 1
notas = [7.0, 7.0, 5.5, 7.0, 7.0, 8.0, 6.0, 1.5, 8.0, 4.5, 7.5, 8.0, 
         2.0, 2.0, 8.0, 0.0, 0.0, 7.0, 6.5, 5.0, 6.5, 6.0, 5.0, 6.5, 
         2.0, 2.0, 6.0, 6.0, 8.0, 0.0, 3.5, 2.0, 6.0, 8.0, 3.0, 7.0, 
         3.0, 0.0, 9.0, 4.5, 8.5, 2.0, 3.0]


print(f"Moda: {max(notas, key=notas.count)}")

Moda: 7.0


In [ ]:
import statistics

mean = statistics.mean(notas)
median = statistics.median(notas)
mode = statistics.mode(notas)
var = statistics.variance(notas)
std = statistics.stdev(notas)

print(f"Média:{mean:14.4f}\nMediana:{median:12.4f}\nModa:{mode:15.4f}\nVariância:{var:10.4f}\nDesvio Padrão:{std:5.4f}")

Média:        5.0000
Mediana:      6.0000
Moda:         7.0000
Variância:    7.2738
Desvio Padrão:2.6970


In [ ]:
import pandas as pd

notas_pd = pd.DataFrame(notas, columns=['Notas'])
notas_pd
notas_pd.describe()

Notas
count  43.000
mean    5.000
std     2.697
min     0.000
25%     2.500
50%     6.000
75%     7.000
max     9.000

In [ ]:
# datetime
from datetime import datetime
today = datetime.now()
today

datetime.datetime(2022, 10, 21, 10, 57, 59, 106678)

In [ ]:
#formatando data
datetime.now().strftime('%d/%m/%Y %H:%M:%S')

'21/10/2022 10:58:01'

In [ ]:
date = datetime.now().strftime('%Y-%m-%d')
date

'2022-10-21'

In [ ]:
import random

random.choice(notas)

0.0

In [ ]:
random.random()

0.5830313708304052

In [ ]:
from random import randint

randint(1, 999)

320

#### Primeira Lib

In [ ]:
# Soma
soma(3,2)

NameError: name 'soma' is not defined

In [ ]:
from biblioteca import soma

In [ ]:
soma(3,2)

5

- ### 1.3 Linguagem de alto e baixo nível


- Baixo Nível
- Alto Nível
- E o python? Low Code
- Qual a Melhor? Vantagens e Desvantagens
    - Numpy: escrito em C

# <font color=green|black> Parte II – Por que Numpy? </font> 

- ### 2.1 Objetivo da biblioteca
            
        2.1.1 Realizar operações em arrays
            2.1.1.1 Array é uma estrutura multidimensional que possibilita armazenar dados na memória do computador
            2.1.1.2 Cada item localizado nessa estrutura pode ser encontrado por meio de um esquema de indexação
            2.1.1.3 Estrutura homogênea de dados: sempre o mesmo formato
        2.1.2 Ser o centro do ecossistema científico no Python.

<img src='https://i.stack.imgur.com/NWTQH.png' height="100%" width="500" style="margin-left: auto;margin-right: auto">

- ### 2.2 Vantagens
        
        2.2.1 Ocupar menos memória
        2.2.2 Mais velocidade
        2.2.3 Facilicitar execução de cálculos numéricos

- ### 2.3 Utilidade
        
        2.3.1 Machine Learning 
        2.3.2 Pandas, SciPy, Matplotlib etc.
        2.3.3 Processamento de Imagem e Computação Gráfica
        
- ### 2.4 Curiosidades
        
        2.4.1 A primeira imagem de buraco negro foi obtida com Numpy
              Utilizou-se telescópio cujo tamanho computacional é igual ao da Terra
        2.4.2 As ondas gravitacionais foram encontradas utilizando os cálculos Numpy

<img src='https://img.ifunny.co/images/9de9a8180790b5f18412d0ff8ba9b11ee9e05cc9112132970641b35beb149479_1.jpg' height="100%" width="500" style="margin-left: auto;margin-right: auto">

# <font color=green|black> Parte III – Aplicações </font> 

- ### 3.1 Primeiros passos

In [ ]:
# 3.1.1 Installing NumPy 

#pip install numpy #ou
!pip install numpy

In [ ]:
# 3.1.2 Import NumPy

import numpy as np

In [ ]:
# 3.1.3 Criar 1D array (string)

arr_str = np.array(['FEA', 'FAU', 'IME', 'POLI', 'ECA', 'FFLCH'])
arr_str


array(['FEA', 'FAU', 'IME', 'POLI', 'ECA', 'FFLCH'], dtype='<U5')

In [ ]:
# 3.1.4 Criar 1D array (float)

arr_float = np.array([0.3, 13.9, 29.6, -109.2, 98.4, 0.0087])
arr_float


array([ 3.000e-01,  1.390e+01,  2.960e+01, -1.092e+02,  9.840e+01,
        8.700e-03])

In [ ]:
# 3.1.5 Criar 1D array (integer)

arr_int = np.array([0, 10, 20, 30, 40, 50])
arr_int


array([ 0, 10, 20, 30, 40, 50])

In [ ]:
# 3.1.6 Criar 1D array (boolean)

arr_bool = np.array([False, True, True, False, True, True])
arr_bool


array([False,  True,  True, False,  True,  True])

In [ ]:
# Obs.: todos esses arrays são da classe Numpy

print(type(arr_str))
print(type(arr_float))
print(type(arr_int))
print(type(arr_bool))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# 3.1.7 Testar array com estrutura heterogênea
# Perceber no output que todos os elementos são transformados em string

arr_teste = np.array(['FEA', 0.3, 0, False])
arr_teste

array(['FEA', '0.3', '0', 'False'], dtype='<U32')

In [ ]:
# 3.1.8 Testar operação matemática com array heterogênea

arr_teste += 1

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('int32')) -> None

In [ ]:
arr_int +=1
arr_int

array([ 1, 11, 21, 31, 41, 51])

- ### 3.2 Array vs Lista
        
        3.2.1 Similaridades: armazenam dados, é possível alterá-los, indexa-los e dividi-los
        3.2.2 Diferenças: lista armazena dados heterogêneos e é built-in enquanto array é homogêneo e instalado
        3.2.2 Por que optar por array?
            3.2.2.1 Maior flexibilidade nos cálculos matemáticos
            3.2.2.2 Mais velocidade
            3.2.2.3 Menor armazenamento
        3.2.3 Comparação

<img src='https://static.mundoeducacao.uol.com.br/mundoeducacao/2021/12/area-do-triangulo.jpg' height="100%" width="300" style="margin-left: auto;margin-right: auto">

In [ ]:
# Numpy arrays e vetores em R

In [ ]:
# Duas listas disponíveis para calcular as áreas de triângulos

b = [2.0, 5.0, 9.0, 3.0, 12.0]
h = [0.5, 9.0, 3.2, 4.8, 7.7]

In [ ]:
# Calcular a área do triângulo utilizando listas

(b * h)/2

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
# Nem cálculos mais simples como apenas somar as duas listas funcionam

b + h

[2.0, 5.0, 9.0, 3.0, 12.0, 0.5, 9.0, 3.2, 4.8, 7.7]

In [ ]:
# Tampouco funciona subtraí-las 

b - h 

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
# 3.2.3.1 Descobrir as áreas dos triângulos utilizando as listas disponíveis

indice = 0
area = []

while indice < 5:
  area.append((b[indice] * h[indice])/2)
  indice += 1

print(area)

[0.5, 22.5, 14.4, 7.199999999999999, 46.2]


In [ ]:
# Dica: utilizar list comprehension e unir com zip

[((b*h)/2) for b, h in zip(b, h)]

[0.5, 22.5, 14.4, 7.199999999999999, 46.2]

In [ ]:
# 3.2.3.2 Descobrir as áreas dos triângulos utilizando numpy array

# Converter as listas em array
b_arr = np.array(b)
h_arr = np.array(h)

print(b_arr, h_arr)

[ 2.  5.  9.  3. 12.] [0.5 9.  3.2 4.8 7.7]


In [ ]:
# Calcular sem a necessidade de loop/list comprehension/zip

(b_arr * h_arr)/2

array([ 0.5, 22.5, 14.4,  7.2, 46.2])

In [ ]:
# É possível realizar qualquer operação com numpy array, como soma

b_arr + 1

array([ 3.,  6., 10.,  4., 13.])

In [ ]:
# Subtração

h_arr - 2

array([-1.5,  7. ,  1.2,  2.8,  5.7])

In [ ]:
# Divisão etc.

b_arr / h_arr

array([4.        , 0.55555556, 2.8125    , 0.625     , 1.55844156])

- ### 3.3 Criar Numpy Arrays 

In [ ]:
# 3.3.1 Array preenchido com 0's

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# 3.3.2 Array preenchido com 1's

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# 3.3.3 Array vazio
# Cria array aleatório e é mais rápido que 0's e 1's 

np.empty(3)

array([5.4e-323, 1.1e-322, 1.6e-322])

In [ ]:
# 3.3.4 Array sequencial
# Obs.: o último elemento não é considerado, neste caso, o 10

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 3.3.5 Array sequencial com intervalos uniformemente espaçados

np.arange(0, 20, 5)

array([ 0,  5, 10, 15])

In [ ]:
# 3.3.6 Array sequencial com valores que são espaçados linearmente em um intervalo especificado

np.linspace(0, 22, num = 5)

array([ 0. ,  5.5, 11. , 16.5, 22. ])

In [ ]:
# 3.3.7 Array com valores aleatórios entre 0 e 1 

# 2 linhas e 4 colunas 

np.random.random((2, 4))

array([[0.11987202, 0.77319478, 0.93405994, 0.06249842],
       [0.17653474, 0.46132224, 0.91423586, 0.41408376]])

In [ ]:
# 3.3.8 Array identidade

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- ### 3.4 Manipular Numpy Arrays

In [ ]:
# Considere estes dois numpy arrays

a = np.array([5, 4, 3, 2, 1])
b = np.array([10, 9, 8, 7, 6])

In [ ]:
# 3.4.1 Unir os dois arrays

c = np.concatenate((a, b))
c

array([ 5,  4,  3,  2,  1, 10,  9,  8,  7,  6])

In [ ]:
# 3.4.2 Colocar em ordem crescente

c_crescente = np.sort(c)
c_crescente

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 3.4.3 Filtrar os elementos divisíveis por 2

c_crescente[c_crescente % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [ ]:
# 3.4.4 Filtrar os elementos divisíveis por 2 e por 5

c_crescente[(c_crescente % 2 == 0) & (c_crescente % 5 == 0)]

array([10])

In [ ]:
# 3.4.5 Substituir os elementos que não são divisíveis por 3 pelo número 0

np.where(c_crescente % 3 == 0, c_crescente, 0)

array([0, 0, 3, 0, 0, 6, 0, 0, 9, 0])

- ### 3.5 Operações com Numpy Arrays

In [ ]:
import time # medir eficiência

In [ ]:
# 3.5.1 Criar um array aleatória com 1 bilhão de elementos entre R$ 0 e R$ 1.000
# Esse array representa preço de fechamento de um portfólio de ativos da FEA.Dev
start_time = time.time()

ativos_dev = np.random.randint(0,1001, size = 1_000_000_000)

end_time = time.time()
print(f"Result calculated in {(end_time - start_time)//60} minutes and {(end_time - start_time)%60} seconds")
# Result calculated in 0.0 minutes and 6.3211987018585205 seconds

Result calculated in 0.0 minutes and 17.091297149658203 seconds


In [ ]:
import random # não necessário caso já tenha importado antes
import time
start_time = time.time()


lista = []
for i in range(1_000_000_000):
    lista.append(random.randint(0,1001))

end_time = time.time()
print(f"Result calculated in {(end_time - start_time)//60} minutes and {(end_time - start_time)%60} seconds")

In [ ]:
len(lista)

In [ ]:
# Verificar se realmente há 1 bilhão de elementos no array criado (len)

len(ativos_dev)

1000000000

In [ ]:
# Verificar se realmente há 1 bilhão de elementos no array criado (shape)

ativos_dev.shape

(1000000000,)

In [ ]:
# 3.5.2 Observar os primeiros 100 elementos do array

ativos_dev[0:100]

array([770, 186, 529, 855, 952,  34,  55, 776, 100, 461, 741, 518, 750,
       539, 231, 125, 301, 603, 159, 279, 633, 670, 258, 567, 761, 313,
        54, 241, 998, 570, 962, 801, 880, 605, 238, 918, 755, 928, 836,
        37, 357, 509,  65, 446, 725, 415, 244,  54, 487,   2,  88, 958,
       287, 165, 155, 663,  43, 333, 387, 396, 863, 881,  32, 189,  67,
       823, 494,  86, 322, 704, 326, 624,  99, 222, 738, 378, 271, 591,
       706, 956, 588,  33, 542, 575, 211, 882, 927, 483, 278, 539, 270,
       281, 178, 456, 861, 964, 362, 887, 894,  16])

In [ ]:
# 3.5.3 Encontrar o valor mínimo do array

ativos_dev.min()

0

In [ ]:
# 3.5.4 Encontrar o valor máximo do array

ativos_dev.max()

1000

In [ ]:
# 3.5.5 Encontrar a soma do array

ativos_dev.sum()

1780494883

In [ ]:
# Dica: formatar o número da soma

soma = ativos_dev.sum()

print(f'R$ {soma:,.2f}')

R$ 1,780,494,883.00


In [ ]:
# 3.5.6 Encontrar a média do array

ativos_dev.mean()

499.996701219

- ### 3.6 Compatibilidade entre Arrays

        3.6.1 As arrays precisam ter pelo menos o mesmo nº de colunas
        3.6.2 Exemplo de compatibilidade
        3.6.3 Exemplo de não compatibilidade

In [ ]:
# 3.6.3.1 Compatibilidade entre Arrays (2,5) e (1,5)

a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.array([[10,20,30,40,50]])

print(a.shape, b.shape)

(2, 5) (1, 5)


In [ ]:
# É possível realizar operações matemáticas com arrays compatíveis, como a soma

a + b

array([[11, 22, 33, 44, 55],
       [16, 27, 38, 49, 60]])

In [ ]:
# A soma acumulada

(a + b).cumsum()

array([ 11,  33,  66, 110, 165, 181, 208, 246, 295, 355], dtype=int32)

In [ ]:
# O produto acumulado

(a + b).cumprod()

array([        11,        242,       7986,     351384,   19326120,
        309217920, -241050752, -569993984, 2135065856, -745067520],
      dtype=int32)

In [ ]:
# A variância

(a + b).var()

248.25

In [ ]:
# Desvio Padrão

(a + b).std()

15.75595125658873

In [ ]:
# 3.6.3.2 Não compatibilidade entre Arrays (3,5) e (3,3)

c = np.array([[0, 5, 10, 15, 20], [0, 10, 20, 30, 40], [0, 100, 200, 300, 400]])
d = np.array([[1, 5, 10], [2, 7, 9], [3, 4, 6]])

print(c.shape, d.shape)

(3, 5) (3, 3)


In [ ]:
# Não é possível realizar operações matemáticas com arrays não compatíveis, como a subtração

c - d

ValueError: operands could not be broadcast together with shapes (3,5) (3,3) 

In [ ]:
# 3.6.3.3 Logo, é possível concluir que arrays (2,1) e (1,2) não são iguais e sequer compatíveis

e = np.array([[8],[16]])
f = np.array([[8,16]])

print(e.shape, f.shape)

(2, 1) (1, 2)


- ### 3.7 Dimensões de Numpy Array

        3.7.1 .flatten()
        3.7.2 .reshape()
        3.7.3 Utilidade em manipular dimensões

In [ ]:
# Observe o array (5,2)

g = np.array([[1, 7], [24, 12], [80, 33], [57, 99], [6, 60]])

print(g, g.shape)

[[ 1  7]
 [24 12]
 [80 33]
 [57 99]
 [ 6 60]] (5, 2)


In [ ]:
# 3.7.1 .flatten() recolhe todos os elementos em apenas uma dimensão

g_flatten = g.flatten()

print(g_flatten, g_flatten.shape)

[ 1  7 24 12 80 33 57 99  6 60] (10,)


In [ ]:
# 3.7.2 .reshape() atribui nova dimensão a um array sem modificar seus elementos

g_reshape = g.reshape(2,5)

print(g_reshape, g_reshape.shape)

[[ 1  7 24 12 80]
 [33 57 99  6 60]] (2, 5)


In [ ]:
# 3.7.3 É útil caso se deseje realizar operações matemáticas com arrays incompatíveis
# No exercício 3.6.3.3 há dois arrays incompatíveis:

e = np.array([[8],[16]]) # (2,1)
f = np.array([[8,16]]) # (1,2)

# .reshape() em algum dos arrays para os deixar compatíveis ao realizar a multiplicação

In [ ]:
# 3.7.3.1 Optar pelo reshape no array 'e'

e.reshape(1,2) * f

array([[ 64, 256]])

In [ ]:
# 3.7.3.2 Optar pelo reshape no array 'f'

e * f.reshape(2,1)

array([[ 64],
       [256]])

- ### 3.8 Tipos de Numpy Array

        3.8.1 Sample Python data types
            3.8.1.1 int
            3.8.1.2 float
        3.8.2 Sample NumPy data types
            3.8.2.1 np.int64
            3.8.2.2 np.int32
            3.8.2.3 np.float64
            3.8.2.4 np.float32
        3.8.3 Hierarquia de coerção
        3.8.4 String
        3.8.5 Boolean
        3.8.6 Conversão


In [ ]:
# 3.8.3.1 Por coerção o type de array com int será o np.int64

np.array([1, 2, 4, 5, 6]).dtype

dtype('int32')

In [ ]:
# 3.8.3.2 Por coerção o type de array com float será o np.int64

np.array([1.32, 5.78, 175.55]).dtype

dtype('float64')

In [ ]:
# 3.8.4 String

np.array(['Universidade', 'de', 'São', 'Paulo']).dtype

dtype('<U12')

In [ ]:
# 3.8.5 Boolean

np.array([True, False, False, False]).dtype

dtype('bool')

In [ ]:
# 3.8.6.1 Conversão

float32_array = np.array([5.32, 3.78, 185.55], dtype = np.float32)
float32_array.dtype

dtype('float32')

In [ ]:
# 3.8.6.1 Conversão

boolean_array = np.array([[False, True], [True, False]], dtype = np.bool_)
boolean_array.astype(np.int32)

array([[0, 1],
       [1, 0]])

- ### 3.9 Random

        3.9.1 Import Random
        3.9.2 Numpy Random

In [ ]:
# Considere a seguinte lista

nomes = ['Ana', 'Gustavo', 'Thais', 'Natalia', 'Julio', 'Max', 'Felipe', 'Alan', 'Paulo', 'Maria', 'Maysa', 'Kevyn']

In [ ]:
# 3.9.1 Import Random

import random

# Escolher aleatoriamente três nomes

random.sample(nomes, 3)

['Thais', 'Maysa', 'Julio']

In [ ]:
# 3.9.2 Numpy Random

# Escolher aleatoriamente três nomes

np.random.choice(nomes, size = 3)

array(['Max', 'Maysa', 'Maria'], dtype='<U7')